CC=g++
CFLAGS=-g -std=gnu++98
#CFLAGS=-g -std=c++0x
LFLAGS=-o

all:
	$(CC) $(CFLAGS) $(LFLAGS) random_sentence random_sentence.cpp grammar.cpp

#test:
#	./random_sentence grammars/*.g

clean:
	rm random_sentence
